blueprints/admin.py
from blueprints.utils import is_user_logged_in, is_admin
from flask import (
    Blueprint,
    render_template
)


admin_page = Blueprint('admin_page', __name__, template_folder="templates")


@admin_page.route("/admin", methods=['POST', 'GET'])
@is_user_logged_in
@is_admin
def admin():
    return render_template("admin/admin.html", title="Administration")

blueprints/authentification.py
from forms import LoginForm
from passlib.hash import sha256_crypt
from models.model import Model
from models.filter import Filter
from flask import (
    Blueprint,
    render_template,
    url_for, flash,
    redirect,
    request,
    session,
)


authentification = Blueprint('authentification', __name__, template_folder="templates")



@authentification.route('/login', methods=['GET', 'POST'])
def login():
    # if the user is already logged in, redirect to home()
    if "user_logged_in" in session.keys():
        return redirect(url_for("home_page.home"))
    
    form = LoginForm()
    
    if request.method == 'POST' and form.validate_on_submit():
        
        # verify that the user exists
        email = form.email.data
        password = form.password.data
        model = Model("t_users")
        filter = Filter(where=f"`email` = '{email}'")
        query = model.query_one_row(filter=filter)
        
        # if the user exists
        if query is not None:
            db_password = query['password']
            
            # verify that its the right passowrd
            if sha256_crypt.verify(password, db_password):
                
                # set session cookies
                session['user_logged_in'] = True
                session["user_email"] = query['email']
                session["user_username"] = query['username']
                session['files'] = query['files']
                session['fname'] = query['first_name']
                session['lname'] = query['last_name']
                session['gender'] = query['gender']
                session['country'] = query['country']
                session['perms'] = query['permission']


                # if remember me check box is checked, set session to permanent
                if form.remember.data is True:
                    session.permanent = True
                else:
                    session.permanent = False
                
                
                # flash message + redirect to the right page
                flash('Vous êtes maintenant connecté', 'success')
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('home_page.home'))
            
            # error message if the password isn't right
            else:
                flash('Le mot de passe est incorrect', 'danger')
                return render_template('authentification/login.html', title="Login", form=form)
        
        # error message if the email isnt in the database
        else:
            flash('Le compte est introuvable !', 'danger')
            return render_template('authentification/login.html', title="Login", form=form)
    return render_template('authentification/login.html', title="Login", form=form)


# logout page (just clear session)
@authentification.route("/logout")
def logout():
    session.clear()
    flash('Vous êtes maintenant déconnecté', 'success')
    return redirect(url_for('home_page.home'))

blueprints/home.py
from blueprints.utils import is_user_logged_in
from flask import (
    Blueprint,
    render_template
)


home_page = Blueprint('home_page', __name__, template_folder="templates")

posts = [
    {
        'author' : 'asdf',
        'title' : 'asdf',
        'date_posted' : '2018',
        'content':'asdf'
    },
    {
        'author' : 'asdf',
        'title' : 'sadf',
        'date_posted' : '2019',
        'content':'asdf'
    }
]


# home page
@home_page.route('/')
def home():
    return render_template('home/home.html',posts=posts, title="Home", sidebar=True)


# about the blog page
@home_page.route('/about/')
@is_user_logged_in
def about():
    return render_template('home/about.html',title="About", sidebar=True)

blueprints/registration.py
from forms import RegistrationForm
from passlib.hash import sha256_crypt
from models.model import Model
from models.filter import Filter
from flask import (
    Blueprint,
    render_template,
    url_for, flash,
    redirect,
    request,
)


registration = Blueprint('registration', __name__, template_folder="templates")


# register page
@registration.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    
    # if the form is valid, insert data in the database
    if request.method == 'POST' and form.validate_on_submit():
        
        # get country's id
        model = Model("t_countries")
        filter = Filter(where=f"`name` = '{form.country.data}'")
        country_id = model.query_one_row(filter = filter)['id']
        if not isinstance(country_id, int):
            flash("Something went wrong..")
            return render_template('register/register.html', title="S'inscrire", form=form)
        
        # get gender's id
        model = Model("t_genders")
        filter = Filter(where=f"`gender` = '{form.gender.data}'")
        gender_id = model.query_one_row(filter = filter)['id']
        if not isinstance(gender_id, int):
            flash("Something went wrong..")
            return render_template('register/register.html', title="S'inscrire", form=form)
        
        fname = str(form.fname.data).replace('"', r'\"')
        fname = fname.replace("'", r"\'")
        
        lname = str(form.lname.data).replace('"', r'\"')
        lname = fname.replace("'", r"\'")
        
        email = str(form.email.data).replace('"', r'\"')
        email = email.replace("'", r"\'")
        
        username = str(form.username.data).replace('"', r'\"')
        username = username.replace("'", r"\'")
        
        # dict insert datas
        insert = {
            'permission'                : 1,
            'first_name'                : fname,
            'last_name'                 : lname,
            'email'                     : email,
            'country'                   : country_id,
            'username'                  : username,
            'password'                  : sha256_crypt.hash(str(form.password.data)),
            'reset_password_permission' : "no_reset",
            'files'                     : "admin.png",
            'gender'                    : gender_id,
            'reset_password_random'     : "Default_value"
        }
        
        # insert datas
        model = Model("t_users")
        sql_query, query = model.insert_into_single_record(fields_values=insert, return_sql_query=True)
        
        # if the query was not successful
        if query is not True:
            
            sql_query = sql_query.replace('"', r'\"')
            sql_query = sql_query.replace("'", r"\'")
            query_str = str(query)
            query_str = query_str.replace('"', r'\"')
            query_str = query_str.replace("'", r"\'")
            
            insert_log = {
                'log_type_id'   : Model("t_log_types").query_one_row(filter=Filter(where="`log_type` = 'add_user'"), fields= ['id'])['id'],
                'sql_executed'  : sql_query,
                'success'       : 0,
                'error_message' : query_str
            }
            
            res = Model("t_logs").insert_into_single_record(fields_values=insert_log)
            print(res,0)
            # error message if duplicate entry
            if query.args[0] == 1062:
                if "username" in query.args[1]:
                    flash(f'Le nom d\'utilisateur {form.username.data} existe déjà ! Veuillez en choisir un autre','danger')
                if "email" in query.args[1]:
                    flash(f'L\'email {form.email.data} existe déjà ! Veuillez en choisir un autre','danger')
            
            # basic error message
            else:
                flash(f'Une erreur est survenue lors de la création du compte de {form.username.data} ! Veuillez contacter le webmaster !','danger')
            return render_template('register/register.html', title="S'inscrire", form=form)
        
        # account created correctly
        else:
            
            sql_query = sql_query.replace('"', r'\"')
            sql_query = sql_query.replace("'", r"\'")
            query_str = str(query)
            query_str = query_str.replace('"', r'\"')
            query_str = query_str.replace("'", r"\'")
            
            insert_log = {
                'log_type_id'   : Model("t_log_types").query_one_row(filter=Filter(where="`log_type` = 'add_user'"), fields= ['id'])['id'],
                'sql_executed'  : sql_query,
                'success'       : 1,
            }
             
            sql_query, res = Model("t_logs").insert_into_single_record(fields_values=insert_log, return_sql_query=True)
            print(res,1, sql_query)
            
            flash(f'Compte crée pour {form.username.data} !','success')
            return redirect(url_for('home_page.home'))
        
    return render_template('register/register.html', title="S'inscrire", form=form)


# INSERT INTO t_logs (`log_type_id`, `sql_executed`, `success`) VALUES (14, 'INSERT INTO t_users (`permission`, `first_name`, `last_name`, `email`, `country`, `username`, `password`, `reset_password_permission`, `files`, `gender`, `reset_password_random`) VALUES (1, 'dsfafsafas', 'dsfafsafas', 'a@b.com', 10, 'asdfasdfasdfasdfa', '$5$rounds=535000$ZQVt8SdJQFeWylxp$xynzCfETKtTNennQOfkECh/rZ94jBQ9EL6.Ds.Cxp0D', 'no_reset', 'admin.png', 2, 'Default_value')', 1)

templates/layout.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css') }}">

        {% if title %}
            <title>Blog Flask - {{ title }}</title>
        {% else %}
            <title>Blog Flask</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{{ url_for('home_page.home') }}">Home</a>
                            <a class="nav-item nav-link" href="{{ url_for('home_page.about') }}">About</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if session.user_logged_in %}
                                {% if session.perms == 3 %}
                                    <a class="nav-item nav-link" href="{{ url_for('admin_page.admin') }}">Admin</a>
                                {% endif %}
                                <a class="nav-item nav-link" href="{{ url_for('account_page.account') }}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('authentification.logout') }}">logout</a>
                                {% if session.perms == 3 %}
                                    <a class="nav-item nav-link" href="{{ url_for('registration.register') }}">Register</a>
                                {% endif %}
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('authentification.login') }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('registration.register') }}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                {% if sidebar == True %}
                    <div class="col-md-8">
                {% else %}
                    <div class="col-md-12">
                {% endif %}
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                {% if sidebar == True %}
                    <div class="col-md-4">
                        <div class="content-section">
                            <h3>Our Sidebar</h3>
                            <p class='text-muted'>You can put any information here you'd like.
                                <ul class="list-group">
                                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                                    <li class="list-group-item list-group-item-light">Announcements</li>
                                    <li class="list-group-item list-group-item-light">Calendars</li>
                                    <li class="list-group-item list-group-item-light">etc</li>
                                </ul>
                            </p>
                        </div>
                    </div>
                {% endif %}
            </div>
          </main>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </legend>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn, btn-outline-info")}}
            </div>
            <small class="test-muted">
                <a href="#">Forgot password ?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account ? <a class="ml-2" href="{{ url_for('register') }}">Sign up now !</a>
        </small>
    </div>
{% endblock content %}

templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} <!-- CRF token -->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Rejoignez le blog dès aujourd'hui !</legend>
                    <!-- username label + field -->
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- fname label + field -->
                    <div class="form-group">
                        {{ form.fname.label(class="form-control-label") }}
                        {% if form.fname.errors %}
                            {{ form.fname(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.fname.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.fname(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- lname label + field -->
                    <div class="form-group">
                        {{ form.lname.label(class="form-control-label") }}
                        {% if form.lname.errors %}
                            {{ form.lname(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.lname.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.lname(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- gender label + field -->
                    <div class="form-group">
                        {{ form.gender.label(class="form-control-label") }}
                        {% if form.gender.errors %}
                            {{ form.gender(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.gender.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.gender(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- country label + field -->
                    <div class="form-group">
                        {{ form.country.label(class="form-control-label") }}
                        {% if form.country.errors %}
                            {{ form.country(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.country.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.country(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- email label + field -->
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- confirm email label + field -->
                    <div class="form-group">
                        {{ form.confirm_email.label(class="form-control-label") }}
                        {% if form.confirm_email.errors %}
                            {{ form.confirm_email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- password label + field -->
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- confirm password label + field -->
                    <div class="form-group">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
            </fieldset>
            <!-- submit button -->
            <div class="form-group">
                {{ form.submit(class="btn, btn-outline-info")}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Vous avez déjà un compte ? <a class="ml-2" href="{{ url_for('login') }}">Connectez vous !</a>
        </small>
    </div>
{% endblock content %}